// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhrdnkykdrbrdyeqtmio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRocmRua3lrZHJicmR5ZXF0bWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzAwMjgsImV4cCI6MjA2MzYwNjAyOH0.EkxFe_F0oQ4PpwFbAlC10bE7x2s3kNjH9Il72Ly_xg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);